### ISSUE TITLE
Dense Conv in first layer for ResNet50.

### ISSUE THREAD

**Issue by hopef** [zyxxmu/LBC#6]
Hi author, 

For ResNet50:
I see LBC used **Dense Conv** in the first layer. 
However, SR-STE used **Sparse Conv** in the first layer. 
Will it make a significant difference?

**Comment by zyxxmu** [comment]
Thanks for your interest in our work. Firstly, the impact of sparsifying the first layer on performance is not significant. The reason we do not sparsify the first layer is to comply with NVIDIA's hardware setting, because the first layer in a convolutional neural network usually only has three channels, which does not meet the n:m requirement. This is also the implementation by NVIDIA's official team (refer to the white paper of NVIDIA A100).

**Comment by hopef** [comment]
Thanks for your reply.

I am testing this configuration based on your excellent project.
In most of my experiments, this configuration can bring 0.1%~0.15% improvement.
But in some other experiments, it didn't bring benefits.

Thanks for the explanation. Have a nice day.
